### ISSUE TITLE
About hand part 

### ISSUE THREAD

**Issue by xy370283** [YoungSeng/UnifiedGesture#1]
Thanks for the outstanding work!
I have a question: have you evaluated the performance of VQVAE-based method on hands part generation? When I used VQVAE, I found that the generated gesture of hands was quite poor, while the Diffusion method performed better in generating hands.

**Comment by YoungSeng** [comment]
This work does not take into account the hand posture; however, as far as I know, a direct codebook representation of the movement does work generally as you say, so one could try to use a codebook and then a separate representation of the hand posture, etc: [Vector Quantized Diffusion Model with CodeUnet for Text-to-Sign Pose Sequences Generation](https://arxiv.org/pdf/2208.09141.pdf).

**Comment by xy370283** [comment]
Thank you for your reply. I will refer to the paper you mentioned.
