### ISSUE TITLE
Hierarchical_XTransformer

### ISSUE THREAD

**Issue by 223d** [YoungSeng/UnifiedGesture#2]
Hi，May I ask Hierarchical_ How is XTransformer installed?

**Comment by YoungSeng** [comment]
Actually we don't use Xtransformer, see `requirements.txt`.

**Comment by 223d** [comment]
@YoungSeng 
Hi ，I encountered ModuleNotFoundError while running the inference.py program: No module named 'Hierarchical_ XTransformer '，

May I ask if you know the reason?

**Comment by YoungSeng** [comment]
This file is not actually used, it was used for testing before, sorry for the confusion, please use `sample.py`, see the Readme file for details.
