### ISSUE TITLE
Question about the cartoon visualization 

### ISSUE THREAD

**Issue by leon532** [YoungSeng/UnifiedGesture#4]
Thanks for sharing the code.

May I ask how to visualize the cartoon animation in the paper and demo video?   

like this

<img width="472" alt="截屏2023-10-19 17 48 24" src="https://github.com/YoungSeng/UnifiedGesture/assets/2986699/a1218ad2-1e61-4499-9cb4-cdaab21a60a5">

**Comment by YoungSeng** [comment]
Download the desired character model from Mixamo: https://www.mixamo.com/#/?page=2&type=Character, and use Blender to generate the animation. You may refer to this [video](https://github.com/YoungSeng/DiffuseStyleGesture/blob/master/visualize_gesture_using_Blender.md).

**Comment by leon532** [comment]
@YoungSeng Thanks a lot for your hand-by-hand instruction. That's so great.

**Comment by leon532** [comment]
@YoungSeng By the way, how do you obtain the Nvidia Audio2gesture results? using the Omniverse Interface?
