### ISSUE TITLE
RL training

### ISSUE THREAD

**Issue by RobinWitch** [YoungSeng/UnifiedGesture#5]
Hello, a nice work ! And thank you to sharing code generously !
Do you have a plan to release your RL training code ?

**Comment by YoungSeng** [comment]
Thank you for your interest in this work, which will be made public as soon as it is well organized.

**Comment by YoungSeng** [comment]
The code for the reinforcement learning section has been uploaded, please check it out.

**Comment by RobinWitch** [comment]
Thank you very much !
